config/routes.rb
require 'sidekiq/web'

Solve::Application.routes.draw do
  root 'problems#index'

  resources :problems, only: [:index, :show] do
    resources :solutions
  end

  namespace 'admin' do
    resources :problems do
      resources :tests
    end
  end

  resources :users, only: [:index, :show, :create, :update] do
    collection do
      post 'login'
      get 'login_cli'
      delete 'logout'
    end
  end

  get 'users/key/:key', to: 'users#key'
  get 'languages', to: 'languages#index'
  get 'cli', to: 'root#cli'

  mount Sidekiq::Web, at: '/sidekiq'

end

app/models/problem.rb
class Problem < ActiveRecord::Base
  has_many :solutions, inverse_of: :problem, dependent: :destroy
  has_many :tests, inverse_of: :problem, dependent: :destroy

  def participants
    self.solutions.select(:user_id).uniq
  end
end

app/controllers/admin/problems_controller.rb
module Admin
  class ProblemsController < Admin::ApplicationController
    before_action :set_problem, only: [:show, :edit, :update, :destroy]

    # GET /admin/problems
    # GET /admin/problems.json
    def index
      @problems = Problem.all
    end

    # GET /admin/problems/1
    # GET /admin/problems/1.json
    def show
    end

    # GET /admin/problems/new
    def new
      @problem = Problem.new
    end

    # GET /admin/problems/1/edit
    def edit
    end

    # POST /admin/problems
    # POST /admin/problems.json
    def create
      @problem = Problem.new(problem_params)

      respond_to do |format|
        if @problem.save
          format.html { redirect_to admin_problem_path(@problem), notice: 'Problem was successfully created.' }
          format.json { render action: 'show', status: :created, location: @problem }
        else
          format.html { render action: 'new' }
          format.json { render json: @problem.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /admin/problems/1
    # PATCH/PUT /admin/problems/1.json
    def update
      respond_to do |format|
        if @problem.update(problem_params)
          format.html { redirect_to admin_problem_path(@problem), notice: 'Problem was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @problem.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /admin/problems/1
    # DELETE /admin/problems/1.json
    def destroy
      @problem.destroy
      respond_to do |format|
        format.html { redirect_to problems_url }
        format.json { head :no_content }
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_problem
      @problem = Problem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def problem_params
      params.require(:problem).permit(:name, :description)
    end
  end
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  before_action :set_problem, only: [:show]

  # GET /problems
  # GET /problems.json
  def index
    @problems = Problem.all
  end

  # GET /problems/1
  # GET /problems/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_problem
      @problem = Problem.find(params[:id])
    end
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/views/problems/_form.html.erb
<%= form_for(@problem) do |f| %>
  <% if @problem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@problem.errors.count, "error") %> prohibited this problem from being saved:</h2>

      <ul>
      <% @problem.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <legend>Problem Definition</legend>
    <div class="row">
      <div class="small-12 columns">
        <%= f.label :name %><br>
        <%= f.text_field :name %>
      </div>
    </div>
    <div class="row">
      <div class="small-12 columns">
        <%= f.label :description %><br>
        <%= f.text_area :description, style: 'height: 250px;' %>
      </div>
    </div>
  </fieldset>

  <div class="row">
    <div class="small-12 columns">
      <%= f.submit class: 'button' %>
    </div>
  </div>
<% end %>

app/views/problems/_test_case.html.erb
<fieldset>
  <div class="row">
    <div class="small-12 columns">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
  </div>
  <div class="row">
    <div class="small-6 columns">
      <%= f.label :input %>
      <%= f.text_field :input %>
    </div>
    <div class="small-6 columns">
      <%= f.label :output %>
      <%= f.text_field :output %>
    </div>
  </div>
</fieldset>

app/views/problems/edit.html.erb
<div class="row">
  <div class="small-12 columns">
    <h1>Editing problem</h1>

    <%= render 'form' %>

    <%= link_to 'Show', @problem %> |
    <%= link_to 'Back', problems_path %>
  </div>
</div>

app/views/problems/index.html.erb
<div class="row">
  <div class="small-12 columns">
    <h1>Problems <small>Gotta solve 'em all!</small></h1>

    <table style="width: 100%;">
      <thead>
        <tr>
          <th style="width: 40px;">ID</th>
          <th>Problem Name</th>
          <th style="width: 100px;">Participants</th>
          <th style="width: 100px;">Solutions</th>
        </tr>
      </thead>
      <tbody>
        <% @problems.each do |problem| %>
        <tr>
          <td><%= problem.id %></td>
          <td><%= link_to problem.name, problem, 'data-no-turbolink' => true %></td>
          <td><%= problem.participants.count %></td>
          <td><%= problem.solutions.count %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="small-4 columns">
  </div>
</div>

app/views/problems/new.html.erb
<div class="row">
  <div class="small-12 columns">
    <h1>New problem</h1>
    <%= render 'form' %>
    <%= link_to 'Back', problems_path %>
  </div>
</div>

app/views/problems/show.html.erb
<div class="row">
  <div class="small-12 columns">
    <h1><%= @problem.name %></h1>
  </div>
</div>

<div class="row">
  <div class="small-12 large-8 columns">
    <div class="row">
      <div class="small-12 columns">
        <h3 class="subheader">Problem Description</h3>
        <p>
          <%= simple_format(@problem.description) %>
        </p>
      </div>
    </div>
  </div>

  <div class="small-12 large-4 columns">
    <h3 class="subheader">Problem stats</h3>
    <ul style="list-style: none;">
      <li><strong>Solutions:</strong> <%= @problem.solutions.count %></li>
    </ul>
  </div>
</div>

<div class="row">
  <div class="small-12 columns">
    <h3 class="subheader">Submit your solution!</h3>
    <p>
      Using the command line tool of your choice:
      <pre>solve problem <%= @problem.id %> &lt;language&gt; &lt;solution&gt;</pre>
    </p>
  </div>
</div>

<div class="row">
  <div class="small-12 columns">
    <h3 class="subheader">Recent Solutions</h3>
    <% if logged_in? %>
    <% if @problem.solutions.where(user: current_user).count > 0 %>
    <% @problem.solutions.order("id DESC").take(5).each do |solution| %>
    <%= render partial: 'solutions/solution', object: solution %>
    <% end %>

    <% if @problem.solutions.count > 5 %>
    <%= link_to 'See all solutions', problem_solutions_path(@problem), class: 'small button' %>
    <% end %>

    <% else %>
    <p>You have to first submit your own solution to this problem before you can see other people's solutions.</p>
    <% end %>
    <% else %>
    <p>You must be logged in and have submitted your own solution before you can see other people's solutions.</p>
    <% end %>
  </div>
</div>