config/routes.rb
require 'sidekiq/web'

Solve::Application.routes.draw do
  root 'problems#index'

  resources :problems, only: [:index, :show] do
    resources :solutions
  end

  namespace 'admin' do
    resources :problems do
      resources :tests
    end
  end

  resources :users, only: [:index, :show, :create, :update] do
    collection do
      post 'login'
      get 'login_cli'
      delete 'logout'
    end
  end

  get 'users/key/:key', to: 'users#key'
  get 'languages', to: 'languages#index'
  get 'cli', to: 'root#cli'

  mount Sidekiq::Web, at: '/sidekiq'

end

app/models/problem.rb
class Problem < ActiveRecord::Base
  has_many :solutions, inverse_of: :problem, dependent: :destroy
  has_many :tests, inverse_of: :problem, dependent: :destroy

  def participants
    self.solutions.select(:user_id).uniq
  end
end

app/controllers/admin/problems_controller.rb
module Admin
  class ProblemsController < Admin::ApplicationController
    before_action :set_problem, only: [:show, :edit, :update, :destroy]

    # GET /admin/problems
    # GET /admin/problems.json
    def index
      @problems = Problem.all
    end

    # GET /admin/problems/1
    # GET /admin/problems/1.json
    def show
    end

    # GET /admin/problems/new
    def new
      @problem = Problem.new
    end

    # GET /admin/problems/1/edit
    def edit
    end

    # POST /admin/problems
    # POST /admin/problems.json
    def create
      @problem = Problem.new(problem_params)

      respond_to do |format|
        if @problem.save
          format.html { redirect_to admin_problem_path(@problem), notice: 'Problem was successfully created.' }
          format.json { render action: 'show', status: :created, location: @problem }
        else
          format.html { render action: 'new' }
          format.json { render json: @problem.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /admin/problems/1
    # PATCH/PUT /admin/problems/1.json
    def update
      respond_to do |format|
        if @problem.update(problem_params)
          format.html { redirect_to admin_problem_path(@problem), notice: 'Problem was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @problem.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /admin/problems/1
    # DELETE /admin/problems/1.json
    def destroy
      @problem.destroy
      respond_to do |format|
        format.html { redirect_to problems_url }
        format.json { head :no_content }
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_problem
      @problem = Problem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def problem_params
      params.require(:problem).permit(:name, :description)
    end
  end
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  before_action :set_problem, only: [:show]

  # GET /problems
  # GET /problems.json
  def index
    @problems = Problem.all
  end

  # GET /problems/1
  # GET /problems/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_problem
      @problem = Problem.find(params[:id])
    end
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/views/admin/problems/_form.html.erb
<%= form_for [:admin, @problem] do |f| %>
  <% if @problem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@problem.errors.count, "error") %> prohibited this problem from being saved:</h2>

      <ul>
      <% @problem.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <legend>Problem Definition</legend>
    <div class="row">
      <div class="small-12 columns">
        <%= f.label :name %><br>
        <%= f.text_field :name %>
      </div>
    </div>
    <div class="row">
      <div class="small-12 columns">
        <%= f.label :description %><br>
        <%= f.text_area :description, style: 'height: 250px;' %>
      </div>
    </div>
  </fieldset>

  <div class="row">
    <div class="small-12 columns">
      <%= f.submit class: 'button' %>
    </div>
  </div>
<% end %>

app/views/admin/problems/_test_case.html.erb
<fieldset>
  <div class="row">
    <div class="small-12 columns">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
  </div>
  <div class="row">
    <div class="small-6 columns">
      <%= f.label :input %>
      <%= f.text_field :input %>
    </div>
    <div class="small-6 columns">
      <%= f.label :output %>
      <%= f.text_field :output %>
    </div>
  </div>
</fieldset>

app/views/admin/problems/edit.html.erb
<div class="row">
  <div class="small-12 columns">
    <h1>Editing problem</h1>

    <%= render 'form' %>

    <%= link_to 'Show', @problem %> |
    <%= link_to 'Back', problems_path %>
  </div>
</div>

app/views/admin/problems/index.html.erb
<div class="row">
  <div class="small-8 columns">
    <h1>Problems</h1>

    <table style="width: 100%;">
      <thead>
        <tr>
          <th>Problem Name</th>
          <th>Solutions</th>
          <th>Pass Rate</th>
        </tr>
      </thead>
      <tbody>
        <% @problems.each do |problem| %>
        <tr>
          <td><%= problem.name %></td>
          <td><%= problem.solutions.count %></td>
          <td>...</td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="small-4 columns">
  </div>
</div>

<div class="row">
  <div class="small-12 columns">
    <%= link_to 'New Problem', new_admin_problem_path %>
  </div>
</div>

app/views/admin/problems/new.html.erb
<div class="row">
  <div class="small-12 columns">
    <h1>New problem</h1>
    <%= render 'form' %>
    <%= link_to 'Back', problems_path %>
  </div>
</div>

app/views/admin/problems/show.html.erb
<div class="row">
  <div class="small-12 columns">
    <h1><%= @problem.name %></h1>
  </div>
</div>

<div class="row">
  <div class="small-12 large-7 columns">
    <p>
      <%= simple_format(@problem.description) %>
    </p>
    <h2 class="subheader">Test Cases</h2>
    <table style="width: 100%;">
      <thead>
        <tr>
          <th>Name</th>
          <th>Input</th>
          <th>Output</th>
          <th style="width: 50px;">Edit</th>
      </thead>
      <tbody>
        <% @problem.tests.each do |test| %>
        <tr>
          <td><%= test.name %></td>
          <td><%= test.input %></td>
          <td><%= test.output %></td>
          <td><%= link_to 'Edit', edit_admin_problem_test_path(@problem, test), class: 'small button', style: 'margin-bottom: 0;' %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="small-12 large-5 columns">
    <div class="panel">
      <h3>Add a test case</h3>
      <%= render partial: 'admin/tests/form', locals: { test: @problem.tests.build } %>
    </div>
  </div>
</div>