config/routes.rb
require 'sidekiq/web'

Solve::Application.routes.draw do
  root 'problems#index'

  resources :problems, only: [:index, :show] do
    resources :solutions
  end

  namespace 'admin' do
    resources :problems do
      resources :tests
    end
  end

  resources :users, only: [:index, :show, :create, :update] do
    collection do
      post 'login'
      get 'login_cli'
      delete 'logout'
    end
  end

  get 'users/key/:key', to: 'users#key'
  get 'languages', to: 'languages#index'
  get 'cli', to: 'root#cli'

  mount Sidekiq::Web, at: '/sidekiq'

end

app/models/solution.rb
class Solution < ActiveRecord::Base
  has_many :test_runs, inverse_of: :solution, dependent: :destroy
  belongs_to :user, inverse_of: :solutions
  belongs_to :problem, inverse_of: :solutions
  belongs_to :language, inverse_of: :solutions

  def correct
    self.test_runs.each do |test_run|
      return false unless test_run.success
    end
  end
end

app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController
  before_action :set_solution, only: [:show, :edit, :update, :destroy]

  # GET /problems/1/solutions
  # GET /problems/1/solutions.json
  def index
    @problem = Problem.find(params[:problem_id])
    @solutions = @problem.solutions.order('id DESC')
  end

  # GET /problems/1/solutions/1
  # GET /problems/1/solutions/1.json
  def show
  end

  # GET /problems/1/solutions/new
  def new
    @solution = Solution.new
  end

  # GET /problems/1/solutions/1/edit
  def edit
  end

  # POST /problems/1/solutions
  # POST /problems/1/solutions.json
  def create
    @language = Language.where(key: solution_params['language']).take
    if @language
      params[:solution][:language_id] = @language.id
      params[:solution].delete(:language)

      @problem = Problem.find(params.require(:problem_id))
      @user = User.where(api_key: params.require(:api_key)).take

      @solution = Solution.new(solution_params)
      @solution.user = @user
      @solution.problem = @problem
      @solution.language = @language

      respond_to do |format|
        if @solution.save
          TestWorker.perform_async(@solution.id)

          format.html { redirect_to @solution, notice: 'Solution was successfully created.' }
          format.json { render action: 'show', status: :created, location: [@solution.problem, @solution] }
        else
          format.html { render action: 'new' }
          format.json { render json: @solution.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        language_string = ''
        Language.all.each do |language|
          language_string += "#{language.key}\t#{language.name}\n"
        end

        format.json { render json: { error: "Unsupported language\nSupported languages:\n#{language_string}" }, status: 400 }
      end
    end
  end

  # PATCH/PUT /problems/1/solutions/1
  # PATCH/PUT /problems/1/solutions/1.json
  def update
    respond_to do |format|
      if @solution.update(solution_params)
        params[:solution][:test_runs].each do |test_run|
          @solution.test_runs.create(test_run)
        end

        format.html { redirect_to @solution, notice: 'Solution was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @solution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /problems/1/solutions/1
  # DELETE /problems/1/solutions/1.json
  def destroy
    @solution.destroy
    respond_to do |format|
      format.html { redirect_to solutions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_solution
      @solution = Solution.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def solution_params
      params.require(:solution).permit(:problem_id, :language, :code, :tested, :test_runs)
    end
end

app/helpers/solutions_helper.rb
module SolutionsHelper
  def language_highlight_class(key)
    language =
      case key
      when 'python2', 'python3'
        'python'
      else
        key
      end

    "language-#{language}"
  end
end

app/views/solutions/_form.html.erb
<%= form_for(@solution) do |f| %>
  <% if @solution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@solution.errors.count, "error") %> prohibited this solution from being saved:</h2>

      <ul>
      <% @solution.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :problem_id %><br>
    <%= f.number_field :problem_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/solutions/_solution.html.erb
<div class="panel">
  <div>
    <strong><%= solution.language.name %></strong> solution by <strong><%= solution.user.username %></strong>
  </div>
  <pre style="background-color: white; border: 1px solid #ccc; font-size: 80%;"><code class="<%= language_highlight_class(solution.language.key) %>"><%= solution.code.sub('<?', '&lt;?').html_safe %></code></pre>
  <% if solution.tested %>
  <% if solution.correct %>
  <span style="font-size: 120%; color: green; font-weight: bold;">100% Correct! (<%= solution.test_runs.where(success: true).count %>/<%= solution.test_runs.count %>)</span>
  <% else %>
  <span style="font-size: 120%; color: red; font-weight: bold;"><%= (solution.test_runs.where(success: true).count.to_f / solution.test_runs.count).round(4) * 100 %>% Correct! (<%= solution.test_runs.where(success: true).count %>/<%= solution.test_runs.count %>)</span>
  <% end %>
  <% else %>
  <span style="font-size: 120%; font-weight: bold;">Queued to be tested...</span>
  <% end %>
</div>

app/views/solutions/edit.html.erb
<h1>Editing solution</h1>

<%= render 'form' %>

<%= link_to 'Show', @solution %> |
<%= link_to 'Back', solutions_path %>

app/views/solutions/index.html.erb
<div class="row">
  <div class="small-12 columns">
    <h1>Solutions to <%= link_to @problem.name, @problem %></h1>
    <% @solutions.each do |solution| %>
    <%= render partial: 'solutions/solution', object: solution %>
    <% end %>
  </div>
</div>

app/views/solutions/new.html.erb
<h1>New solution</h1>

<%= render 'form' %>

<%= link_to 'Back', solutions_path %>

app/views/solutions/show.html.erb
<div class="row">
  <div class="small-12 columns">
    <h1>Solutions to <%= @solution.problem.name %></h1>
  </div>
</div>